### ISSUE TITLE
LED illumination attribute

### ISSUE THREAD

**Issue by katecrombie** [pds-data-dictionaries/ldd-img#20]
The Hayabusa2 MASCOT imager Mascam uses LED sources to illuminate the imaging target.  They will require an attribute that can be used to describe these LEDs.  It should be something like "active_led" and allow the user to input a wavelength for the illumination source.

**Comment by TheOneTrueCDC** [comment]
Hi @katecrombie I've just implemented some new classes to house this LED illumination information. Please take a look and provide your feedback!

If you click on the link above this comment, where it says "Issue #20 : Test implementation...", you'll be able to view a diff that shows the changes I made.

I'm also attaching a visual representation of the new classes.
![Screen Shot 2019-10-03 at 7 43 14 PM](https://user-images.githubusercontent.com/3208931/66177390-21aa7900-e616-11e9-9a9d-5a2c2a6bc8ba.png)

**Comment by TheOneTrueCDC** [comment]
@katecrombie One concern I have is that the IM may not have the correct units of measure to describe the wavelength. Here's a list of the currently supported units: https://pds.nasa.gov/datastandards/documents/im/v1/index_1C00.html#24%C2%A0%C2%A0Unit%20of%20Measure%20Classes

**Comment by katecrombie** [comment]
@TheOneTrueCDC I think this call will work.  The LEDs are described in wavelength units of nanometers, so we should be good.  Thanks.

**Comment by TheOneTrueCDC** [comment]
@katecrombie In that case, I can edit the illumination_wavelength to use Units_of_Length with "nm" as the value. Doest that work? https://pds.nasa.gov/datastandards/documents/im/v1/index_1C00.html#class_pds_units_of_length

**Comment by katecrombie** [comment]
@TheOneTrueCDC your solution sounds good to me.

**Comment by TheOneTrueCDC** [comment]
@katecrombie I've implemented these changes and will release the updated IMG dictionary as soon as the new PDS build is released.

**Comment by katecrombie** [comment]
@TheOneTrueCDC Thanks!  I'll work with the MASCOT team to get this implemented in their labels.

**Comment by thareUSGS** [comment]
Appears to have been previously added in 1.7.0.0
