### ISSUE TITLE
gain_number data type

### ISSUE THREAD

**Issue by benjhirsch** [pds-data-dictionaries/ldd-img#24]
Only integer values are valid for the gain_number attribute; is there a reason for this? SBN has a data provider that will be supplying FITS images with non-integer values for gain, so if the data type can be expanded to ASCII_Real, that would be helpful.

**Comment by msbentley** [comment]
I also have a data provider to the PSA who would like to specify either a non-integer gain, or else both the commanded (integer) gain, and the result of a calculated (ASCII_Real) gain...

**Comment by thareUSGS** [comment]
update in https://github.com/pds-data-dictionaries/ldd-img/pull/34
