### ISSUE TITLE
add <GOP_Frames>, Group Of Pictures (GOP)

### ISSUE THREAD

**Issue by thareUSGS** [pds-data-dictionaries/ldd-img#26]
Per Bob D. (for MSAM also needed to support MSL and M2020 going forward).

Under Video add:
     
```
   <GOP_Frames>  List of frames for a Group Of Pictures (GOP)
     <GOP_Frame>  Information on single Group Of Pictures (GOP) frame
       <gop_offset>  Position of this frame within the GOP
       <gop_length>  Length of this frame in the GOP
     </GOP_Frame>
   </GOP_Frames>
```

**Comment by rgdeen** [comment]
Scratch the above.  Here's the current suggested plan:

Add the following keywords under Video:

frame_index: The frame_index attribute specifies the sequence number of this frame in the context of the entire video, i.e. the first frame of the video would be index 1, up to frame_count.

gop_frame_count: Videos can be broken into Groups Of Pictures (GOP)s, which group a number of frames together.  The gop_frame_count attribute specifies the number of frames in this GOP.

gop_frame_index: Videos can be broken into Groups of Pictures (GOP)s, which group a number of frames together.  The gop_frame_index attribute specifies the index of this frame within its GOP (starting at 1).  This is distinct from frame_index, which is the index into the video as a whole.

gop_start_index: Videos can be broken into Groups of Pictures (GOP)s, which group a number of frames together.  The gop_start_index attribute specifies the index of the first frame of the GOP (starting at 1).  Thus, frame_index = gop_start_index + gop_frame_index - 1.

----

So for normal, non-gop movies, you have:

<Video>
        <frame_count> 5
        <frame_index> 3 

For gop movies, you have:

<Video>
        <frame_count> 20
        <frame_index> 13
        <gop_frame_count> 5
        <gop_frame_index> 3
        <gop_start_index> 11

**Comment by thareUSGS** [comment]
https://github.com/pds-data-dictionaries/ldd-img/pull/38

only added frame_index and gop_start_index under Video. gop_frame_count and gop_frame_index already existed.
