### ISSUE TITLE
Add Spatial_Filter to img (and Image_Filter)

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/ldd-img#28]
Spatial_Filter

This class should be a child of Imaging.  Also for completeness a child of Commanded_Parameters, although I doubt it will be used there.  It should extend the Data_Processing class.  Cardinality 0:any (there could be multiple types of filtering that are done).

def:  The Spatial_Filter class specifies what kind of spatial filtering has been done on the image.  Spatial filtering looks at the geometry of pixels (e.g. XYZ or range values) rather than their intensity (cf. Image_Filter).

(note that we don't have an Image_Filter yet but we will obviously need one, if you want to add it now that would be okay).

Children for Spatial_Filter (obviously more can be added as needed):

filter_window_line: The size in pixels of the window used for filtering in the line dimension.  If the window varies across the image, this could contain the average window or initial window, as needed by the specific algorithm.

filter_window_sample: The size in pixels of the window used for filtering in the sample dimension.  If the window varies across the image, this could contain the average window or initial window, as needed by the specific algorithm.

max_filter_window_line: The maximum size in pixels of the window used for filtering in the line dimension.  If the window is constant across the image, filter_window_line should be used instead.

max_filter_window_sample: The maximum size in pixels of the window used for filtering in the sample dimension.  If the window is constant across the image, filter_window_sample should be used instead.

min_filter_window_line: The minimum size in pixels of the window used for filtering in the line dimension.  If the window is constant across the image, filter_window_line should be used instead.

min_filter_window_sample: The minimum size in pixels of the window used for filtering in the sample dimension.  If the window is constant across the image, filter_window_sample should be used instead.

(note: I don't really like separating line/samp here everywhere since for the current purpose they're the same... but I think for future use we kind of have to.  It would be ugly in the DD to have e.g. window plus window_line and window_samp, although perhaps cleaner in the labels).

Example of use (oh, add img: everywhere of course):

```
<Spatial_Filter>
   <processing_algorithm>Range_Filter_Deen_2020</processing_algorithm>
   <average_filter_window_line>1.87743</average_filter_window_line>
   <average_filter_window_sample>1.87743</average_filter_window_sample>
   <max_filter_window_line>1.99181</max_filter_window_line>
   <max_filter_window_sample>1.99181</max_filter_window_sample>
   <min_filter_window_line>1.76447</max_filter_window_line>
   <min_filter_window_sample>1.76447</max_filter_window_sample>
</Spatial_Filter>

```
If you want to add Image_Filter at this time (might as well), let's start with the same 6 children... same definitions apply.  (note that processing_algorithm, as well as other things, is inherited from the Data_Processing superclass).

Nick, the processing algorithm is unfortunately not in the label.  If the derived_image_type is XYZ_FILTER_MAP and all three labels exist (AVERAGE_FILTER_WINDOW, MIN_FILTER_WINDOW, MAX_FILTER_WINDOW), then put in the processing algorithm above as a constant.

**Comment by thareUSGS** [comment]
Pull https://github.com/pds-data-dictionaries/ldd-img/pull/37
