### ISSUE TITLE
Add Image_Mask to img

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/ldd-img#29]
Image_Mask

First, a question on the DD.  Data_Processing_File defines the basics for a file.  That's great.  That is then subclassed in several other files, e.g. Companding_File.  They all (identically) extend ("xs:restriction") DPF, but then repeat the contents!  Is that needed? Since DPF has the sequence of description, choice (int|ext ref), name), does that have to be repeated in the subclasses?  I mean, it seems like Companding_File could just be:

```
  <xs:complexType name="Companding_File">
    <xs:annotation>
      <xs:documentation>The Companding _File class specifies the file
        containing the decompanding (inverse LUT) table used to process
        the data.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:restriction base="img:Data_Processing_File">
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

```
without the sequence?  That's how the Data_Processing subclasses work.. they do not repeat what's in DP.  This is not a big deal, it'll work this way, it just seems pedantically wrong in the DD.

Anyway... back to Image_Mask.  It should similarly go in both Imaging and Commanded_Parameters, and similarly subclass from Data_Processing.

def:  The Image_Mask specifies how pixels were masked (removed) from an image.  Masks are typically used to suppress results in areas where they don't belong, for example masking off spacecraft hardware or removing pixels that did not meet some processing threshold.

Children:

Image_Mask_File: This class identifies a file used for image masking. The mask_type defines the type of file; if mask_type is missing then "image" is assumed.

(cardinality: 0-any)

Image_Mask_File derives from Data_Processing_File and has the following additional child:

mask_type: This identifies the type of mask file.  Most masks are of "image" type, this means it is an image of the same size as the current image containing mask information at each pixel.  A mask_type of "description" indicates that the file describes the mask in some other way depending on the processing_algorithm.

horizon_mask_elevation: Specifies the elevation above which the image is masked off.
(angular units (degrees)) 

Example of use (add img: prefixes except on name):

```
<Image_Mask>
  <processing_algorithm>MSL rover mask</processing_algorithm>
  <horizon_mask_elevation unit="deg">90.0</horizon_mask_elevation> 
  <Image_Mask_File>
    <mask_type>description</mask_type>
    <name>MSL_rover_filter.xml</name>
  </Image_Mask_File>
  <Image_Mask_File>
    <mask_type>description</mask_type>
    <name>MLF_405851630MXY_S0050104AUT_04096D1.MXML</name>
  </Image_Mask_File>
</Image_Mask>
```

While it would be better to use an internal reference here (and the DD will allow that), it's problematic because the MSL_rover_filter.xml file is renamed to MSL_rover_filter.xmlx in the cal dir for delivery, since PDS does not allow .xml for data files.  Therefore the actual file does not exist in the delivery, so we can't built a lidvid to it.  And I do NOT want to special-case this in the templates!!  My SIS does say that the .xmlx's in the cal dir have to be renamed back to .xml for use so we're covered there.  In principle, we could build a lidvid to the second file, but that would require special-casing in the template that I would really rather avoid doing.  Thus, <name> here.  Future missions may get better labels where this can be done "properly".  But this kind of thing is why I made sure we had <name> available in the Data_Processing_File.

**Comment by thareUSGS** [comment]
@jordanpadams Can you maybe comment on rgdeen's first question above on Data_Processing_File.

**Comment by thareUSGS** [comment]
@rgdeen Not sure I pushed Image_Make and Image_Mask_File in correctly. Can you review the built schema for needed changes.

I built the schema since I think I got all recent requested updates added. The new schema file is available to look at from here: https://github.com/pds-data-dictionaries/ldd-img/tree/master/build/1.D.0.0_1.7.0.0

**Comment by jordanpadams** [comment]
@rgdeen per your comment, this is simply because there are no additional "extensions" to the original Data_Processing_File class, so it is really just a direct one-to-one inheritance. if you add an additional attribute to the IngestLDD, it looks like the others you are referring to:

```
  <xs:complexType name="Companding_File">
    <xs:annotation>
      <xs:documentation>The Companding _File class specifies the file
        containing the decompanding (inverse LUT) table used to process
        the data.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="img:Data_Processing_File">
        <xs:sequence>
          <xs:element name="foo" type="img:foo" minOccurs="0" maxOccurs="1"> </xs:element>
        </xs:sequence>
        <!-- Begin assert statements for schematron - Enumerated Values -->
        <!-- <xs:assert test="img:foo = ('Companded', 'Expanded', 'None')"/> -->
        <!-- End assert statements for schematron - Enumerated Values -->
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
```

**Comment by jordanpadams** [comment]
also, @rgdeen to clarify, doesn't Data_Processing_File require an internal reference?

**Comment by rgdeen** [comment]
@jordanpadams so yeah I get that if you add an element you see just the added element.  But currently CompandingFile looks like:

```
  <xs:complexType name="Companding_File">
    <xs:annotation>
      <xs:documentation>The Companding _File class specifies the file
        containing the decompanding (inverse LUT) table used to process
        the data.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:restriction base="img:Data_Processing_File">
        <xs:sequence>
          <xs:element name="description" type="pds:description" minOccurs="0" maxOccurs="1"> </xs:element>
          <xs:choice minOccurs="1" maxOccurs="1">
            <xs:element ref="pds:Internal_Reference"> </xs:element>
            <xs:element ref="pds:External_Reference"> </xs:element>
          </xs:choice>
          <xs:element name="name" type="pds:name" minOccurs="0" maxOccurs="1"> </xs:element>
        </xs:sequence>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>
```
where the <description< and <name> and references exactly duplicate what's in Data_Processing_File.  Yes this is direct inheritance with no additions but it doesn't make sense that you have to repeat all the elements in that case.  Are you saying that you DO have to repeat them?  In that case, what's the point of the inheritance?

**Comment by rgdeen** [comment]
other issues... no the references are specifically NOT required for DPF.  There's an alternate filename option.  References are preferred but the filename is an escape hatch.

**Comment by rgdeen** [comment]
and @thareUSGS elevation should be -90 to +90 not 0 to 90

**Comment by rgdeen** [comment]
Now that I think about it I wonder if we should add an element to the ImageMask, something like image_mask_polarity?  that says whether 0 is transparent or opaque.   Generally masks are zero/non-zero but it's not always consistent which way they are to be interpreted.  Might take some thought to define this fully....?

**Comment by jordanpadams** [comment]
@rgdeen 

>> where the <description< and and references exactly duplicate what's in Data_Processing_File
Understood. It may very well be a bug in LDDTool that is unnecessary. What I am poking at here is I don't think it matters. Ignoring the XSD, your label shouldn't care and it should validate the same.

>> other issues... no the references are specifically NOT required for DPF. There's an alternate filename option. References are preferred but the filename is an escape hatch.

"escape hatch" meaning the file was used in processing or operations? if that is the case, this should somehow be called out explicitly. otherwise putting it in the label is more confusing than helpful.

**Comment by thareUSGS** [comment]
@rgdeen -90 to 90 makes more sense - horizon_mask_elevation updated and re-pushed built files.

BTW, many applications that use masks (generally 8bit) also allow 1 -254 to allow for an opacity gradient. 0 is generally defined as NoData and 255 means valid. Just more to describe although for PDS I don't think an opacity gradient would be used. e.g. https://gdal.org/development/rfc/rfc15_nodatabitmask.html

**Comment by rgdeen** [comment]
@jordanpadams here's the writeup for DPF that explains references vs filenames:
```
      <xs:documentation>The Data_Processing_File class contain
        attributes which identify a file containing calibration data
        that was applied to the science data. It is not intended to be
        used on its own; rather it is intended to be extended by classes
        specific to a particular type of file, such as Flat_Field_File.
        Note that the "name" attribute is the name of the file; this
        attribute should only be used if the file is either not included
        in an archive, or if the delivery status is unknown by the data
        provider. The External_Reference or Internal_Reference class
        should be used instead of name if at all
        possible.</xs:documentation>
```
hopefully that explains it.  There are situations where it is useful to note the file but it might not be archived, or you don't know whether it is or not when the label is built.

**Comment by rgdeen** [comment]
@thareUSGS yeah the opacity gradient thing is why I punted on describing fully.  ;-)  Do you think it's worth trying to work out values for this?  We could start with something like zero_transparent, zero_opaque, and gradient perhaps?

**Comment by rgdeen** [comment]
@thareUSGS other than the polarity question I think the rest of the mask stuff looks okay

**Comment by rgdeen** [comment]
oh except the references need minOccurs=0 in Image_Mask_File per the above, just like all the other DPF's.

**Comment by thareUSGS** [comment]
Changed references to minOccurs=0 in Image_Mask_File and Data_Processing_File.

@rgdeen How about:
- mask_transparent_value  (ASCII_Real)

def. Specifies the pixel value in the mask that will represent transparent (or NoData/null) for the characterized image. This is normally defined as 0 in the mask layer. Once defined, any other value in the mask represents opaque (or valid) in the characterized image. No gradient for now...

updated and re-pushed.

**Comment by rgdeen** [comment]
Sounds okay.  You might say "... represents opaque or translucent (in other words, valid) in the..."

We can punt on more sophisticated descriptions until they're needed.

**Comment by thareUSGS** [comment]
updated def. in pull https://github.com/pds-data-dictionaries/ldd-img/pull/45
