### ISSUE TITLE
Add flip to Detector

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/ldd-img#31]
img:Detector has an element detector_to_image_rotation. That's good.  However, 2020 has at least one case (cachecam) where there's a flip, or mirror image.  So I think we need another attribute:

detector_to_image_flip

The detector_to_image_flip attribute indicates whether and how the image was flipped (mirror image) along its optical path through an instrument, from detector to final image orientation.  "Horizontal" means a left-to-right flip, while "Vertical" means a top-to-bottom-flip.  Note that if both this attribute and detector_to_image_rotation exist, the flip is assumed to have happened before the rotation.

Cardinality: 0-1.  Valids: Horizontal, Vertical, None

(note, I wouldn't normally use None, but included for completeness)

BTW the ordering is based on the idea that flips would usually happen due to a mirror, which is external to the camera, while rotations generally happen because the camera is mounted sideways or upside-down... thus in the optical path, flips should happen first.

This is not a MSAM/MSL issue, it's needed only for 2020... just getting ahead of the curve a bit.

**Comment by thareUSGS** [comment]
pull https://github.com/pds-data-dictionaries/ldd-img/pull/35
