### ISSUE TITLE
LDD needs to be updated for v1.14.0.0 of the IM

### ISSUE THREAD

**Issue by jordanpadams** [pds-data-dictionaries/ldd-img#49]
When running with LDDTool v11.2.2, several errors are now thrown by LDDTool when trying to generate IMG dictionaries. This is most likely due to some safeguards added per new CCBs from this build cycle.

```
   ERROR    Init:  - LDD Dictionary_Type not Found:TBD_Ingest_LDD  Defaulting to Discipline
   ERROR    Attribute: <mask_type> - The 'type' attribute must have at least one permissible value.
   ERROR    Attribute: <radiometric_type> - The 'type' attribute must have at least one permissible value.
   ERROR    Attribute: <subframe_type> - The 'type' attribute must have at least one permissible value.
   ERROR    Attribute: <current_value> - A 'nilable' attribute must be a required attribute in at least one class.
   ERROR    Attribute: <erase_count> - A 'nilable' attribute must be a required attribute in at least one class.
   ERROR    Attribute: <voltage_value> - A 'nilable' attribute must be a required attribute in at least one class.
```

**Comment by thareUSGS** [comment]
I was building with v10.2. I will update.

**Comment by jordanpadams** [comment]
@thareUSGS np. i am testing out our new LDD process to-be-instated next build in the fall, which would have already tried to pre-build this for you and thrown an error. i guess this just further highlights the need for this effort.

**Comment by rgdeen** [comment]
what does this mean?
```
A 'nilable' attribute must be a required attribute in at least one class
```
Is it trying to say that if a value is nilable, that is also must be required???

If so that's wrong.  Very, very wrong.  Some users of the class might want to always have the attribute and use nil or not.  Others may want to not have it at all.  There are different semantics between present-and-nil and not-present and you cannot force nilable items to be present.

If this was the case I would strongly recommend not using nilable at all, as it would make the flag completely useless.

I hope I'm misinterpreting this... but if so the error message at least needs to be fixed.

**Comment by thareUSGS** [comment]
I think for these three cases we can simply change to:
    <nillable_flag>false</nillable_flag>
from:
    <nillable_flag>true</nillable_flag>

Since they are all optional, there is no reason to them set to true... That is what I am thinking for now.


https://github.com/pds-data-dictionaries/ldd-img/blob/7e8d535f58c562906b7f927a0aabadda1a5a5965/src/PDS4_IMG_IngestLDD.xml#L638

**Comment by thareUSGS** [comment]
hmm - I am perhaps more confused about
`The type attribute must have at least one permissible value.`

All those shown are non enumerated free text  (ASCII_Short_String_Collapsed).

**Comment by rgdeen** [comment]
In this case, yes.  But if there were users who wanted it nilable, that would force EVERYONE using the class to add it, which would be horrific.  So @jordanpadams can you confirm if I'm understanding this properly and if so, what the rationale is for this and how do we change it back?

**Comment by jordanpadams** [comment]
First off, I believe both of these errors come out of [CCB-204](https://github.com/pds-data-dictionaries/ldd-img/files/4566349/CCB_204.pdf)

The nillable error is basically saying "why make it nillable if you don't require it anywhere". It should probably be more of a warning that an error but not sure if @jshughes has any thoughts there.

The `_type` errors are for best practices with the IM. this has been kind of a thing people talked about but never checked with software. basically if you have an attribute with the name `*_type`, thou shall contain a permissible value list. if you don't want a permissible value list, then you need to change the name to something that more properly indicates it is free form, e.g. `radiometry_type_name`.

the idea for all of these is to enforce consistency across the entire system, not just at the PDS Core namespace level.

**Comment by jordanpadams** [comment]
@rgdeen @thareUSGS sorry for not tagging you. ☝️

**Comment by thareUSGS** [comment]
hmm the *_type update is a little unfortunate. @rgdeen I guess we need new names?
mask_type => mask_description
radiometric_type => radiometric_description
subframe_type => subframe_description

Is this going to impact current labels?

**Comment by rgdeen** [comment]
yes it will impact current labels, including insight.

So there are two different threads here.

1) nilable

This is an easy one.  In some contexts, for some missions, you might want to be able to say value or nil.  In other contexts, value or not present.  Even within one mission, you might want to say it has to be there (value or nil) for instrument A but can be absent for instrument B.

All the rule does is encourage you to have an unused <throwaway_element> in the DD with a required nilable child to get rid of the error.  Or simply not use nilable at all, which is the way I'd go here.

So given this rule, @thareUSGS  let's remove nilable until/unless the rule changes.

2) _type

None of us are smart enough to be able to enumerate all possible types for things like these.  My general philosophy here is to leave it open-ended so new types can be added easily in the future without having to change the DD.

If necessary we could enumerate the names we have now, knowing full well that it is (and will always be) an incomplete list that will have to be updated constantly as new missions come in.  If you're okay with that, I guess we could do that.  I don't like the philosophy but y'all are the ones that are going to have to keep constantly updating IMG et al.

**Comment by thareUSGS** [comment]
I will reject the new "test" pull request with the updated *_type names. https://github.com/pds-data-dictionaries/ldd-img/pull/50
It sounds like that is not an option and you would prefer to keep the names with enumerations. If so I guess we need to gather those acceptable values (even if we need to update them...).

**Comment by rgdeen** [comment]
sigh...

mask_type
description : The referenced file describes the mask using a text or xml based file, as opposed to being an image.
[[ "description" as a type is rather generic but mostly I was thinking that vs image here.  Others can add a specific description format later if they want ]]
[[ this is still changeable as it was added for MSAM, but I don't have any "name" of the format to use here.... ]]

radiometric_type
Spectral Radiance : Radiometric correction results are expressed in units of Spectral Radiance (generally W/m^2/sr/nm)
Scaled Spectral Radiance : Radiometric correction results are expressed as Spectral Radiance, but have subsequently been scaled in some way to compensate for photometric effects (for example, adjusting the brightness as if the sun was at zenith or correcting for the impact of atmospheric opacity (tau)).
[[ we do one or both of those, which it is should be apparent via other labels]

subframe_type
I apparently don't use this but there are suggested values in the description.

**Comment by jordanpadams** [comment]
@rgdeen agree this is a pain, but just something to keep in mind when creating new attributes in the future

**Comment by thareUSGS** [comment]
@rgdeen Sounds like mask_type and subframe_type can be renamed without impact to existing. Although, I'm not sure how to find out is subframe_type has ever been used.

Let's keep radiometric_type with your two enumerations?

**Comment by rgdeen** [comment]
why not keep them all with enumerations?  I mean, it really is the proper thing to do (to elucidate the enums), even if we have to keep updating the DD.

**Comment by thareUSGS** [comment]
Will do. For mask_type the only ones I have are "image" and "description".

**Comment by rgdeen** [comment]
that's all I have for now... which is why I was hesitant to list the enums.  It would be nice if there were a way to indicate that additional values are expected in the future here.

**Comment by thareUSGS** [comment]
updated based on: https://github.com/pds-data-dictionaries/ldd-img/pull/51
