### ISSUE TITLE
Dark_Current_Correction class

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/ldd-img#54]
Need a new class in img DD:

Dark_Current_Correction: Specifies how dark current removal was performed on this image.

It should extend Data_Processing (just like Flat_Field_Correction does) and likewise be a child of both Commanded_Parameters and Imaging. There will be more to add to it later, but currently just these two new keywords, from TELEMETRY (bad place for them, but oh well).

STRIPING_COUNT
Dark_Current_Correction.striping_count - int, valid 0-any
Specifies the number of stripes (N) used during dark current mitigation within image acquisition.
Image “striping” is comprised of reading out the image in N different parts (“stripes”), often using a hardware windowing mode, using N separate exposures (with identical exposure times). These successive stripes correspond to physically different locations on the CCD. A commandable overlap (M rows) allows each successive row to "cover" the image pixels towards the readout region.

STRIPING_OVERLAP_ROWS
Dark_Current_Correction.striping_overlap_rows - int, valid 0-any
Specifies the number of rows (M) of striping overlap used during dark current mitigation within image acquisition.
Image “striping” is comprised of reading out the image in N different parts (“stripes”), often using a hardware windowing mode, using N separate exposures (with identical exposure times). These successive stripes correspond to physically different locations on the CCD. A commandable overlap (M rows) allows each successive row to "cover" the image pixels towards the readout region.

--  Velocity notes: These keywords should both go under Commanded_Parameters, since they are the commanded values rather than a result. Include img:processing_venueOnboard</> as part of the class, and img:active_flagTrue</> if the count value is non-0. (If the count is 0, omit the entire DCC paragraph).

**Comment by thareUSGS** [comment]
uner "Velocity notes", do you mean the Dark_Current_Correction class should be a component of Commanded_Parameters?

**Comment by rgdeen** [comment]
yes, part of both CP and the non-command. (like everything else in img)

**Comment by thareUSGS** [comment]
Okay that Commanded_Parameters and now Dark_Current_Correction is a component of Imaging. So Dark_Current_Correction could be listed under CP and Imaging...

for Dark_Current_Correction class I assume all need to be listed at least once?

`  
  <DD_Class>
    <name>Dark_Current_Correction</name>
    <version_id>1.0</version_id>
    <local_identifier>Dark_Current_Correction</local_identifier>
    <submitter_name>Trent Hare</submitter_name>
    <definition>Specifies how dark current removal was performed on this image.</definition>
    <abstract_flag>false</abstract_flag>
    <element_flag>false</element_flag>
    <DD_Association>
      <identifier_reference>striping_count</identifier_reference>
      <reference_type>attribute_of</reference_type>
      <minimum_occurrences>1</minimum_occurrences>
      <maximum_occurrences>1</maximum_occurrences>
    </DD_Association>
    <DD_Association>
      <identifier_reference>striping_overlap_rows</identifier_reference>
      <reference_type>attribute_of</reference_type>
      <minimum_occurrences>1</minimum_occurrences>
      <maximum_occurrences>1</maximum_occurrences>
    </DD_Association>
    <DD_Association>
      <identifier_reference>Data_Processing</identifier_reference>
      <reference_type>parent_of</reference_type>
      <minimum_occurrences>1</minimum_occurrences>
      <maximum_occurrences>1</maximum_occurrences>
    </DD_Association>
  </DD_Class>`

**Comment by rgdeen** [comment]
nooooo.... not at all.  Min occurs = 0 across the board.  I almost never do anything else!  ;-)  There are too many variations to insist on having anything.  Also striping is a very specific technique that may not actually be used anywhere else.

**Comment by thareUSGS** [comment]
Just figured if you had to list Dark_Current_Correction you need to set something (all set to min=0). I think this is done.

**Comment by rgdeen** [comment]
yeah but we don't know which.  Also it's quite feasible to set nothing but the active flag to say it's been done, with no details.
