### ISSUE TITLE
OBSERVATION_REQUEST_PARMS for img

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/ldd-img#58]
BAD_PIXEL_REPLACEMENT_FLAG
Detector.bad_pixel_replacement_flag - string, True/False
Specifies whether or not bad pixel replacement processing was requested or completed. If set to True, certain pixels in the image were replaced based on a bad pixel table. See bad_pixel_replacement_table.

BAD_PIXEL_REPLACEMENT_ID
Detector.bad_pixel_replacement_table
Specfies the table number of the bad pixel table used in the bad pixel replacement process. See also bad_pixel_replacement_flag.

-- Detector is maybe not a great superclass for these, but it's not horrible and I couldn't find anything better (and it doesn't make sense to me as a new class). The Detector instance for these should obviously go in the Commanded_Parameters section.

Add <Internal_Reference> as an optional child of Detector. The intent is that it can be used to point at the bad pixel replacement table, using as the reference type data_to_calibration_product or perhaps something more specific, like data_to_bad_pixel_table...

EXPOSURE_SCALE_FACTOR
Exposure.exposure_scale_factor - float, no valid range
Specifies a multiplier to the base exposure time. The base exposure time is either user-commanded or is read from the onboard exposure time table. The resulting number is used by the cameras as the actual commanded exposure time. This scale factor is commonly used during multi-spectral imaging, when the base exposure time is known for one filter and EXPOSURE_SCALE_FACTOR is used to scale the exposure time to levels appropriate for the other filters.
-- Commanded_Parameters section

EXPOSURE_TABLE_ID
Autoexposure.exposure_table - string, no valid
Identifies the exposure table to be used, or that was used. The exposure table provides the seed exposure value to use for each camera for the autoexposure algorithm.

EXPOSURE_TBL_UPDATE_FLAG
Autoexposure.exposure_table_update_flag - string, True/False
Specifies whether or not to update the autoexposure table based on the results of this exposure.

INSTRUMENT_IDLE_TIMEOUT / __UNIT
Detector.instrument_idle_timeout - float, 0-unbounded, unit of time
Specifies the amount of time in seconds the instrument may be idle before powering off the instrument
-- again, Detector isn't great but it's not bad. Commanded_Parameters for this use.

**Comment by thareUSGS** [comment]
I can't tell what type of values and range for your added "bad_pixel_replacement_table"

**Comment by thareUSGS** [comment]
For now set - bad_pixel_replacement_table to string (ASCII_Short_String_Collapsed)

**Comment by rgdeen** [comment]
yes I think string is safe there.  The table id could be a string, although I think the current use cases are numeric.
