### ISSUE TITLE
subframe_type

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/ldd-img#59]
subframe_type is defined in img:Subframe but has not yet been used (at least not by us). The description has a sample set of values:

      <xs:documentation> The subframe_type attribute specifies the
        method of subframing performed on the image. These methods may
        vary by mission so the permissible values should be set by the
        mission dictionaries. Example values from MSL include a)
        'Software Only' - Software processsing only. b) 'Hardware
        Compatible' - Use hardware only if compatible. c) 'Hardware Else
        Software' - Use hardware then software. d) 'Subframe Around Sun'
        - If the sun is found, send a subframed image of the sun. If sun
        is not found, send back no image.</xs:documentation>

Although I note that in the latest DD the description is smaller and the valids appear to be listed as actual valids.

The actual values listed for both MSL and M20 are:

b)  “SW_ONLY” - Software processsing only.
c)  “HW_COND” - Use hardware only if compatible.
d)  “HW_SW” - Use hardware then software.
e)  “SUN_NO_IMG” - If the sun is found, send a subframed image of the sun.  If sun is not found, send back no image.
f)  “SUN_FULL” - If the sun is found, send a subframed image of the sun.  If the sun is not found, send back the entire image.

The original description is missing SUN_FULL. But beyond that, is there a reason to change the mapping here? Can we use the MSL/M20 valids? Overly complicating the template to change one set of values for another that's substantially similar seems ... pointless?

So.... is it possible to change the valids here to match what we're actually generating?  Or is it "too late" to do so now?  (I have no idea of the publication status or rules regarding that).  Another option is to list two sets of valids, but I would not be particularly in favor of that.  Or do we suck it up and complicate the velocity templates to do the value translation?

Regardless, we need SUN_FULL or equivalent added to the valid list.

**Comment by thareUSGS** [comment]
Suck it up and update velocity feels like the right thing to do :-)  (and I will add SUN_FULL). Now these can change since it will be tagged at a new version and old archives will list the original version (and values if they were ever used). But that obviously is something to try to avoid.

**Comment by rgdeen** [comment]
Sigh.  Okay so then the valid list would be:

'Software Only' - Software processsing only. == SW_ONLY
'Hardware Compatible' - Use hardware only if compatible. == HW_COND
'Hardware Else Software' - Use hardware then software. == HW_SW
'Subframe Around Sun' - If the sun is found, send a subframed image of the sun. If sun is not found, send back no image. == SUN_NO_IMG
'Sun Subframe Or Full' -  If the sun is found, send a subframed image of the sun. If the sun is not found, send back the entire image. == SUN_FULL

Sound okay?

**Comment by rgdeen** [comment]
Please add "None" to the valid list as well.  Meaning: No subframe requested.
