### ISSUE TITLE
Add focus_distance

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/ldd-img#60]
Add new item to img.Focus :

focus_distance: The nominal focus distance for the instrument in meters. This is often the commanded value, or autofocus seed value, but can also be used to indicate a nominal distance where the connotation of "best" is not appropriate (see best_focus_distance).

Units of meters, cardinality 0:1, range 0..any

**Comment by rgdeen** [comment]
Update: "in meters" -> "in units of length".  We will actually be using mm, but it should make no difference from the DD point of view right?  In other words users could use m or mm (or even km or whatever) as they choose, right?

**Comment by thareUSGS** [comment]
Yes the user can set the units. Why don't make the definition:
The nominal focus distance for the instrument (e.g. in meters).

Units of length, cardinality 0:1, range 0..any

**Comment by rgdeen** [comment]
That's fine.  Or given the use case, "(e.g. in meters or mm)".
