### ISSUE TITLE
Valid values for exposure_type

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/ldd-img#61]
The valid values for exposure_type should be:

MANUAL - manual exposure setting
MANUAL_LAST - use same exposure as the prior image
AUTO - autoexposure is applied by the camera
AUTO_LAST - autoexposure using prior image as a seed
TEST - return a test pattern image
NONE - no exposure requested

The _LAST's are new, and it's unclear whether NONE was actually allowed before.  The description should be reworked since it lists the valid values (or remove the valids from the description in favor of actual enumerated valids?  That's a DD structure question).

Note that I'm suggesting UPPER_CASE style for the values since that matches what's in the VICAR labels.

**Comment by thareUSGS** [comment]
The current use and for most values throughout IMG, it seems "Capital" first letter is used (besides acronyms). Are you good with that?

Not sure I understand your DD question. It is up to you on the use of None. None is not currently allowed -- probably in favor of simply skipping "exposure_type" (if there is nothing to report). I am fine seeing a None for enumerations though.

**Comment by rgdeen** [comment]
NONE was not listed in the description before, and I didn't know if there was an actual valid list, so I was unclear on whether or not it was real.  It should be added, thanks.

Will get back to you on the capitalization shortly.  Checking to see if there's an appropriate macro.

**Comment by rgdeen** [comment]
I tend to prefer ALL_CAPS but that's because I'm a programmer.  I'm okay with the "Mixed Case" if you want.

**Comment by thareUSGS** [comment]
Mixed Case it is (sorry) -- precedence. Closed
