### ISSUE TITLE
Wording change for icer_quality

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/ldd-img#62]
The icer_quality description says nothing.  Here's a better description:

----
For ICER, the quality is the “minloss” parameter, which specifies the minimum number of bit planes that will not be encoded in each subband.  Note that ICER may stop due a byte quota before minloss is achieved, so the actual quality may be less than specified.  Unlike JPEG, a lower number means higher quality.
----

Also the min value is listed as 1, that's incorrect: it should be min=0.  0 is perfectly valid.

**Comment by thareUSGS** [comment]
You imply here decimals are allowed. Currently it is defined as **ASCII_NonNegative_Integer** -- is that correct?

**Comment by rgdeen** [comment]
I do?  No that's not "0.0" that's ") end of sentence... new sentence 0 is perfectly valid".  We have it as an int.

Yes 18 is the max.  I don't quite understand that, seems like it should be 16 given the definition, but that's what the documentation claims.

Note that the generic quality setting (not type-specific) is a float 0-1 but that's not this.

**Comment by thareUSGS** [comment]
"min = 0" period - got it. haha - reminds me of:

Let’s eat, Grandma
vs. 
Let’s eat Grandma

**Comment by rgdeen** [comment]
;-)
