### ISSUE TITLE
Consider adding new IMG attributes to support MESSENGER MDIS migration

### ISSUE THREAD

**Issue by TheOneTrueCDC** [pds-data-dictionaries/ldd-img#8]
Investigate these PDS3 keywords & determine whether to create PDS4 attributes for them.
- MISSING_PIXELS
- SATURATED_PIXEL_COUNT

**Comment by thareUSGS** [comment]
Might as well be consistent. I recommend

- MISSING_PIXEL_COUNT
and Bob stated he also needed
- VALID_PIXEL_COUNT

**Comment by thareUSGS** [comment]
@rgdeen These 3 still needed?

- saturated_pixel_count
- missing_pixel_count
- valid_pixel_count

Any recommended definitions or just go for it and make it similar to below.

And I assume these 3 placed next to here:
https://github.com/pds-data-dictionaries/ldd-img/blob/f8d7dd856ff45eba45eceade17b2b27f724ba59f/src/PDS4_IMG_IngestLDD.xml#L725

**Comment by rgdeen** [comment]
Yeah I still have a need for valid_pixel_count.  I don't need saturated or missing but presumably messenger still does and in any case they are reasonable things to have.  Probably not as children of compression though as I don't think they're compression-related.  Maybe Sampling???  Can't think of anything better....

**Comment by thareUSGS** [comment]
pull https://github.com/pds-data-dictionaries/ldd-img/pull/39

@rgdeen, Do you want to see if the definitions work for you?

**Comment by rgdeen** [comment]
looks reasonable to me, thanks....
